version: '3.9'

services:
  backend:
    build: ./DashboardHospitalBack
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - PORT=3000

  frontend:
    build: ./DashboardHospital
    container_name: frontend
    ports:
      - "5000:80"  # React será servido por nginx en este contenedor
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"  # Aquí expondremos Nginx para servir todo
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
